trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    git config --global user.email "thanesp@mitrphol.com"
    git config --global user.name "mpdev01.test-sync-azure-devops"

    git remote add azure https://Digital-Product-Development@dev.azure.com/Digital-Product-Development/DPD_FromGitHub/_git/test-sync-azure-devops

    git push azure --all
    git push azure --tags

  displayName: Sync GitHub To Azure Repos